--------------------------------------------------------
--  File created - Monday-December-02-2024   
--------------------------------------------------------
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\TABLES\COMMON_ASSET_CONDITION_Q_MAP.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\TABLES\DWO_CLASS_CONDITION_Q_MASTER.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\TABLES\LOAD_COMMON_ASSET_CLEANED_1_ASSET_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\TABLES\LOAD_COMMON_ASSET_CLEANED_2_CONDITION_Q_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\TABLES\LOAD_COMMON_ASSET_CLEANED_3_PERFORMANCE_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\TABLES\LOAD_COMMON_ASSET_CLEANED_4_AMC_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\TABLES\LOAD_COMMON_ASSET_CLEANED_5_COF_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\TABLES\LOAD_COMMON_ASSET_CLEANED_6_PERF_COND_LOF_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\TABLES\LOAD_COMMON_ASSET_CLEANED_7_BRR_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\TABLES\LOAD_COMMON_ASSET_CLEANED_8_CPAL_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\TABLES\LOAD_UNQ_ASSET_CLEANED_1_ASSET_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\TABLES\LOAD_UNQ_ASSET_CLEANED_2_CONDITION_Q_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\TABLES\LOAD_UNQ_ASSET_CLEANED_3_PERFORMANCE_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\TABLES\LOAD_UNQ_ASSET_CLEANED_4_AMC_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\TABLES\LOAD_UNQ_ASSET_CLEANED_5_COF_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\TABLES\LOAD_UNQ_ASSET_CLEANED_6_PERF_COND_LOF_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\TABLES\LOAD_UNQ_ASSET_CLEANED_7_BRR_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\TABLES\LOAD_UNQ_ASSET_CLEANED_8_CPAL_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\TABLES\PARAMETER_MASTER.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\TABLES\T_OUT_ALL_ASSET_CLASS_SEGMENTATION.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\TABLES\UNQ_ASSET_CONDITION_Q_MAP.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\TABLES\VALIDATE_UNQ_ASSET_CONDITION_Q.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\TABLES\WWO_ASSET_TYPES_MASTER.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\TABLES\WWO_CLASS_DESCRIPTION_MASTER.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\TABLES\WWO_COMMON_ASSET_2B_CLEANED.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\TABLES\WWO_COMMON_ASSET_CLEANED_NO_CALC.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\TABLES\WWO_COMMON_ASSET_CLEANED_NO_CALC_CONDITION_Q.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\TABLES\WWO_COMMON_ASSET_CLEANED_NO_CALC_CONDITION_Q_T.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\TABLES\WWO_COMMON_ASSET_CONDITION_SET_Q_MASTER_KEY.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\TABLES\WWO_COMMON_ASSET_PARKED.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\TABLES\WWO_COMMON_ASSET_STATUS.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\TABLES\WWO_CONDITION_SET_Q_MASTER.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\TABLES\WWO_CONDITION_SET_Q_MASTER_KEY.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\TABLES\WWO_CONDITION_SET_Q_MASTER_TRANSPOSE.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\TABLES\WWO_COST_OVERRIDE_MASTER.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\TABLES\WWO_EAM_SYSTEM_EXTRACT_MASTER.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\TABLES\WWO_MATRIX_ANSWERS_MASTER.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\TABLES\WWO_RAW_TAB1_MASTER_DATA.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\TABLES\WWO_RAW_TAB2_MASTER_DATA.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\TABLES\WWO_RECORD_DISCARDED_MASTER.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\TABLES\WWO_SEGMNT_COMMON_ASSET_CLASS_MASTER.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\TABLES\WWO_SEGMNT_UNQ_ASSET_CLASS_MASTER.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\TABLES\WWO_UNQ_ASSET_2B_CLEANED.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\TABLES\WWO_UNQ_ASSET_CLEANED_NO_CALC.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\TABLES\WWO_UNQ_ASSET_CLEANED_NO_CALC_CONDITION_Q.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\TABLES\WWO_UNQ_ASSET_CLEANED_NO_CALC_CONDITION_Q_T.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\TABLES\WWO_UNQ_ASSET_CONDITION_SET_Q_MASTER_KEY.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\TABLES\WWO_UNQ_ASSET_PARKED.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\TABLES\WWO_UNQ_ASSET_STATUS.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\VIEWS\TEST_102_REC.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\VIEWS\TEST_CONVERT.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\VIEWS\T_IN_CLASS_DESCRIPTION_V.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\VIEWS\T_IN_DU_11_ASSETS_DETAIL_V.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\VIEWS\T_IN_DU_11_ASSETS_V.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\VIEWS\T_IN_DU_9_10_CLASS_CATEGORY_INFO_V.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\VIEWS\T_IN_DWO_CONDITION_Q_CLASS_SET_V.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\VIEWS\T_IN_DWO_CONDITION_SET_Q_V.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\VIEWS\T_IN_WWO_ASSET_TYPES_V.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\VIEWS\T_IN_WWO_CLASS_SEGMENTATION_V.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\VIEWS\T_IN_WWO_COMMON_ASSET_ACCEPT_V.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\VIEWS\T_IN_WWO_CONDITION_Q_SOLUTION_V.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\VIEWS\T_IN_WWO_CONDITION_SET_Q_V.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\VIEWS\T_IN_WWO_COST_OVERRIDE_V.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\VIEWS\T_IN_WWO_EAM_SYSTEM_EXTRACT_V.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\VIEWS\T_IN_WWO_MATRIX_ANSWERS_V.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\VIEWS\T_IN_WWO_RAW_TAB1_V.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\VIEWS\T_IN_WWO_RAW_TAB2_V.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\VIEWS\T_TABLE_COUNT_V.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\VIEWS\UNQ_ASSET_FINAL_CONDITION_Q.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\INDEXES\LOAD_UNQ_ASSET_CLEANED_NO_CALC_PK.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\INDEXES\WWO_ASSET_TYPES_MASTER_PK.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\INDEXES\WWO_CONDITION_SET_Q_MASTER_KEY_PK.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\INDEXES\WWO_COST_OVERRIDE_MASTER_PK.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\INDEXES\WWO_ASSET_TYPES_MASTER_PK_1.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\INDEXES\WWO_CONDITION_SET_Q_MASTER_KEY_PK_1.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\INDEXES\WWO_COST_OVERRIDE_MASTER_PK_1.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\INDEXES\LOAD_UNQ_ASSET_CLEANED_NO_CALC_PK_1.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PROCEDURES\UPDATE_SOURCE_TABLE.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGES\PKG_EXECUTE_FULL_REFRESH.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGES\PKG_EXECUTE_P1_ASSET_DATA_REFRESH.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGES\PKG_EXECUTE_P4_UNQ_ASSET_COND_Q_MAP.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGES\PKG_EXECUTE_P5_COMMON_ASSET_COND_Q_MAP.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGES\PKG_EXECUTE_P7_ASSET_CALCULATIONS_REFRESH.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGES\PKG_EXECUTE_P8_CMN_ASSET_CALCULATIONS_REFRESH.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGES\PKG_EXECUTE_P9_LOAD_RESULTS.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGES\PKG_LOAD_1_ASSET_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGES\PKG_LOAD_1_CMN_ASSET_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGES\PKG_LOAD_2_ASSET_CONDITION_Q_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGES\PKG_LOAD_2_CMN_ASSET_CONDITION_Q_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGES\PKG_LOAD_3_ASSET_PERFORMANCE_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGES\PKG_LOAD_3_CMN_ASSET_PERFORMANCE_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGES\PKG_LOAD_4_ASSET_AMC_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGES\PKG_LOAD_4_CMN_ASSET_AMC_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGES\PKG_LOAD_5_ASSET_COF_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGES\PKG_LOAD_5_CMN_ASSET_COF_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGES\PKG_LOAD_6_ASSET_PERF_COND_LOF_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGES\PKG_LOAD_6_CMN_ASSET_PERF_COND_LOF_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGES\PKG_LOAD_7_ASSET_BRR_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGES\PKG_LOAD_7_CMN_ASSET_BRR_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGES\PKG_LOAD_8_ASSET_CPAL_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGES\PKG_LOAD_8_CMN_ASSET_CPAL_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGES\PKG_LOAD_P1A_MASTER_DATA.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGES\PKG_LOAD_P1B_UNQ_ASSET_DATA_INITIAL.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGES\PKG_LOAD_P1C_UNQ_ASSET_DATA_FINAL.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGES\PKG_LOAD_P1D_COMMON_ASSET_DATA_INITIAL.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGES\PKG_LOAD_P1E_COMMON_ASSET_DATA_FINAL.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGE_BODIES\PKG_EXECUTE_FULL_REFRESH.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGE_BODIES\PKG_EXECUTE_P1_ASSET_DATA_REFRESH.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGE_BODIES\PKG_EXECUTE_P4_UNQ_ASSET_COND_Q_MAP.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGE_BODIES\PKG_EXECUTE_P5_COMMON_ASSET_COND_Q_MAP.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGE_BODIES\PKG_EXECUTE_P7_ASSET_CALCULATIONS_REFRESH.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGE_BODIES\PKG_EXECUTE_P8_CMN_ASSET_CALCULATIONS_REFRESH.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGE_BODIES\PKG_EXECUTE_P9_LOAD_RESULTS.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGE_BODIES\PKG_LOAD_1_ASSET_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGE_BODIES\PKG_LOAD_1_CMN_ASSET_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGE_BODIES\PKG_LOAD_2_ASSET_CONDITION_Q_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGE_BODIES\PKG_LOAD_2_CMN_ASSET_CONDITION_Q_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGE_BODIES\PKG_LOAD_3_ASSET_PERFORMANCE_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGE_BODIES\PKG_LOAD_3_CMN_ASSET_PERFORMANCE_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGE_BODIES\PKG_LOAD_4_ASSET_AMC_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGE_BODIES\PKG_LOAD_4_CMN_ASSET_AMC_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGE_BODIES\PKG_LOAD_5_ASSET_COF_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGE_BODIES\PKG_LOAD_5_CMN_ASSET_COF_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGE_BODIES\PKG_LOAD_6_ASSET_PERF_COND_LOF_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGE_BODIES\PKG_LOAD_6_CMN_ASSET_PERF_COND_LOF_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGE_BODIES\PKG_LOAD_7_ASSET_BRR_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGE_BODIES\PKG_LOAD_7_CMN_ASSET_BRR_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGE_BODIES\PKG_LOAD_8_ASSET_CPAL_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGE_BODIES\PKG_LOAD_8_CMN_ASSET_CPAL_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGE_BODIES\PKG_LOAD_P1A_MASTER_DATA.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGE_BODIES\PKG_LOAD_P1B_UNQ_ASSET_DATA_INITIAL.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGE_BODIES\PKG_LOAD_P1C_UNQ_ASSET_DATA_FINAL.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGE_BODIES\PKG_LOAD_P1D_COMMON_ASSET_DATA_INITIAL.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\PACKAGE_BODIES\PKG_LOAD_P1E_COMMON_ASSET_DATA_FINAL.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\BRR_GET_RISK_BASELINE_VALUE.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_AMC_AGE.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_AMC_CA_LIFE_REMAINING.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_AMC_CA_PERCENT_LIFE_CONSUMED.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_AMC_CONDITION_ADJUSTED_USEFULL_LIFE.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_AMC_ESTIMATED_USEFUL_LIFE_EUL.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_AMC_LIFE_REMAINING.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_AMC_PERCENT_LIFE_CONSUMED.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_AMC_PREDICTED_CIP_YEAR.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_AMC_PREDICTED_REPLACEMENT_YEAR.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_ASSET_TYPE_INTIAL_REINVESTMENT_ACTION.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_ASSET_TYPE_MAX_POTENTIAL_LIFE.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_ASSET_TYPE_REHAB_EUL.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_BRR_BR3.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_CIP_COST_OVERRIDE.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_CIP_RECOMMENDED_REINVESTMENT_ACTION.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_COF_RATING.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_COF_SCORE.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_CONDITION_RATING.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_CONDITION_SCORE.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_COST_OVERIDE_ENG_CM_ADMIN_LEGAL_20_PERC.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_COST_OVERIDE_GENERAL_CONDITION_5_PERC.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_COST_OVERIDE_SUBTOTAL.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_COST_OVERRIDE_CONTINGENCY_25.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_COST_OVERRIDE_TOTALCOST.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_CPAL_1_ACTION.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_CPAL_1_ACTION_COST.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_CPAL_1_ACTION_TIMEFRAME_BR1.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_CPAL_1_ACTION_TIMEFRAME_BR2.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_CPAL_1_ACTION_TIMEFRAME_BR3.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_CPAL_2_ACTION.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_CPAL_2_ACTION_COST.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_CPAL_2_ACTION_TIMEFRAME_BR1.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_CPAL_2_ACTION_TIMEFRAME_BR2.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_CPAL_2_ACTION_TIMEFRAME_BR3.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_CPAL_3_ACTION.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_CPAL_3_ACTION_COST.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_CPAL_3_ACTION_TIMEFRAME_BR1.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_CPAL_3_ACTION_TIMEFRAME_BR2.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_CPAL_3_ACTION_TIMEFRAME_BR3.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_CPAL_4_ACTION.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_CPAL_4_ACTION_COST.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_CPAL_4_ACTION_TIMEFRAME_BR1.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_CPAL_4_ACTION_TIMEFRAME_BR2.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_CPAL_4_ACTION_TIMEFRAME_BR3.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_CPAL_NO_OF_REHABS.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_CPAL_REHAB_EUL.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_CPAL_REPLACEMENT_EUL.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_CPAL_TIMEFRAME.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_LOF_RATING.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_LOF_SCORE.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_MIN_SYSTEM_COMMISION_YR.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_PERFORMACE_MATRIX_ANSWERS.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_PERFORMANCE_RATING.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\FUNCTIONS\GET_PERFORMANCE_SCORE.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\CONSTRAINTS\LOAD_COMMON_ASSET_CLEANED_1_ASSET_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\CONSTRAINTS\LOAD_COMMON_ASSET_CLEANED_2_CONDITION_Q_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\CONSTRAINTS\LOAD_COMMON_ASSET_CLEANED_6_PERF_COND_LOF_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\CONSTRAINTS\LOAD_COMMON_ASSET_CLEANED_8_CPAL_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\CONSTRAINTS\LOAD_UNQ_ASSET_CLEANED_1_ASSET_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\CONSTRAINTS\LOAD_UNQ_ASSET_CLEANED_2_CONDITION_Q_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\CONSTRAINTS\LOAD_UNQ_ASSET_CLEANED_6_PERF_COND_LOF_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\CONSTRAINTS\LOAD_UNQ_ASSET_CLEANED_8_CPAL_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\CONSTRAINTS\VALIDATE_UNQ_ASSET_CONDITION_Q.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\CONSTRAINTS\WWO_ASSET_TYPES_MASTER.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\CONSTRAINTS\WWO_COMMON_ASSET_CLEANED_NO_CALC.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\CONSTRAINTS\WWO_COMMON_ASSET_PARKED.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\CONSTRAINTS\WWO_CONDITION_SET_Q_MASTER_KEY.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\CONSTRAINTS\WWO_COST_OVERRIDE_MASTER.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\CONSTRAINTS\WWO_EAM_SYSTEM_EXTRACT_MASTER.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\CONSTRAINTS\WWO_UNQ_ASSET_CLEANED_NO_CALC.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_t\CONSTRAINTS\WWO_UNQ_ASSET_PARKED.sql
