--------------------------------------------------------
--  DDL for View E_CLASS_DESCRIPTION_V
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "COH_DEV_E"."E_CLASS_DESCRIPTION_V" ("CLASS_ID", "CLASS_DESCRIPTION", "ORGANIZATION", "DT_INSERTED") AS SELECT
        trim(class_id),
        trim(class_description),
        trim(organization),
        dt_inserted
    FROM
        e_class_description
;
  GRANT DELETE ON "COH_DEV_E"."E_CLASS_DESCRIPTION_V" TO "COH_DEV_T";
  GRANT INSERT ON "COH_DEV_E"."E_CLASS_DESCRIPTION_V" TO "COH_DEV_T";
  GRANT SELECT ON "COH_DEV_E"."E_CLASS_DESCRIPTION_V" TO "COH_DEV_T";
  GRANT UPDATE ON "COH_DEV_E"."E_CLASS_DESCRIPTION_V" TO "COH_DEV_T";
  GRANT REFERENCES ON "COH_DEV_E"."E_CLASS_DESCRIPTION_V" TO "COH_DEV_T";
  GRANT READ ON "COH_DEV_E"."E_CLASS_DESCRIPTION_V" TO "COH_DEV_T" WITH GRANT OPTION;
  GRANT ON COMMIT REFRESH ON "COH_DEV_E"."E_CLASS_DESCRIPTION_V" TO "COH_DEV_T";
  GRANT QUERY REWRITE ON "COH_DEV_E"."E_CLASS_DESCRIPTION_V" TO "COH_DEV_T";
  GRANT DEBUG ON "COH_DEV_E"."E_CLASS_DESCRIPTION_V" TO "COH_DEV_T";
  GRANT FLASHBACK ON "COH_DEV_E"."E_CLASS_DESCRIPTION_V" TO "COH_DEV_T";
  GRANT MERGE VIEW ON "COH_DEV_E"."E_CLASS_DESCRIPTION_V" TO "COH_DEV_T";
