--------------------------------------------------------
--  DDL for View E_DU_11_ASSETS_V
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "COH_DEV_E"."E_DU_11_ASSETS_V" ("ASSET_ID", "DESCRIPTION", "CLASS_ID", "CATEGORY") AS Select "ASSET_ID","DESCRIPTION","CLASS_ID","CATEGORY" from E_DU_11_ASSETS
;
  GRANT READ ON "COH_DEV_E"."E_DU_11_ASSETS_V" TO "COH_DEV_T" WITH GRANT OPTION;
  GRANT DELETE ON "COH_DEV_E"."E_DU_11_ASSETS_V" TO "COH_DEV_T" WITH GRANT OPTION;
  GRANT INSERT ON "COH_DEV_E"."E_DU_11_ASSETS_V" TO "COH_DEV_T" WITH GRANT OPTION;
  GRANT SELECT ON "COH_DEV_E"."E_DU_11_ASSETS_V" TO "COH_DEV_T" WITH GRANT OPTION;
  GRANT UPDATE ON "COH_DEV_E"."E_DU_11_ASSETS_V" TO "COH_DEV_T" WITH GRANT OPTION;
  GRANT REFERENCES ON "COH_DEV_E"."E_DU_11_ASSETS_V" TO "COH_DEV_T" WITH GRANT OPTION;
  GRANT ON COMMIT REFRESH ON "COH_DEV_E"."E_DU_11_ASSETS_V" TO "COH_DEV_T" WITH GRANT OPTION;
  GRANT QUERY REWRITE ON "COH_DEV_E"."E_DU_11_ASSETS_V" TO "COH_DEV_T" WITH GRANT OPTION;
  GRANT DEBUG ON "COH_DEV_E"."E_DU_11_ASSETS_V" TO "COH_DEV_T" WITH GRANT OPTION;
  GRANT FLASHBACK ON "COH_DEV_E"."E_DU_11_ASSETS_V" TO "COH_DEV_T" WITH GRANT OPTION;
  GRANT MERGE VIEW ON "COH_DEV_E"."E_DU_11_ASSETS_V" TO "COH_DEV_T" WITH GRANT OPTION;
