--------------------------------------------------------
--  DDL for View E_WWO_MATRIX_ANSWERS_V
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "COH_DEV_E"."E_WWO_MATRIX_ANSWERS_V" ("MATRIX", "MATRIX_ANSWERS", "DT_INSERTED") AS SELECT
        trim(matrix),
        trim(matrix_answers),
        dt_inserted
    FROM
        e_wwo_matrix_answers
;
  GRANT DELETE ON "COH_DEV_E"."E_WWO_MATRIX_ANSWERS_V" TO "COH_DEV_T";
  GRANT INSERT ON "COH_DEV_E"."E_WWO_MATRIX_ANSWERS_V" TO "COH_DEV_T";
  GRANT SELECT ON "COH_DEV_E"."E_WWO_MATRIX_ANSWERS_V" TO "COH_DEV_T";
  GRANT UPDATE ON "COH_DEV_E"."E_WWO_MATRIX_ANSWERS_V" TO "COH_DEV_T";
  GRANT REFERENCES ON "COH_DEV_E"."E_WWO_MATRIX_ANSWERS_V" TO "COH_DEV_T";
  GRANT READ ON "COH_DEV_E"."E_WWO_MATRIX_ANSWERS_V" TO "COH_DEV_T" WITH GRANT OPTION;
  GRANT ON COMMIT REFRESH ON "COH_DEV_E"."E_WWO_MATRIX_ANSWERS_V" TO "COH_DEV_T";
  GRANT QUERY REWRITE ON "COH_DEV_E"."E_WWO_MATRIX_ANSWERS_V" TO "COH_DEV_T";
  GRANT DEBUG ON "COH_DEV_E"."E_WWO_MATRIX_ANSWERS_V" TO "COH_DEV_T";
  GRANT FLASHBACK ON "COH_DEV_E"."E_WWO_MATRIX_ANSWERS_V" TO "COH_DEV_T";
  GRANT MERGE VIEW ON "COH_DEV_E"."E_WWO_MATRIX_ANSWERS_V" TO "COH_DEV_T";
