--------------------------------------------------------
--  DDL for View E_WWO_RAW_TAB2_V
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "COH_DEV_E"."E_WWO_RAW_TAB2_V" ("ASSET_ID", "ASSET_STAGE", "LOCATION", "LOCATION_ID", "EAM_LOCATION", "SYSTEM", "SYSTEM_ID", "EAM_SYSTEM", "SYSTEM_CLASS_CODE", "POSITION", "POSITION_ID", "POSITION_CLASS", "COLUMN1", "POSITION_CLASS_CODE", "EAM_POSITION", "SUBPOSITION", "SUBPOSITION_ID", "SUB_POSITION_CLASS", "COLUMN22", "SUB_POSITION_CLASS_CODE", "EAM_SUBPOSITION", "ASSET", "ASSET_IN_EAM", "DISCIPLINE", "CLASS", "CLASS_ID", "CATEGORY", "INSTALL_DATE", "POSITION_COMMISSION_DATE", "STATUS", "ASSESSMENT_DATE", "OPERATOR_PRESENT", "LOF_CAPACITY", "LOF_RELIABILITY", "LOF_OM", "LOF_OBSOLESCENCE", "LOF_REDUNDANCY", "LOF_ERUL", "ATTRIBUTE_Q1", "ATTRIBUTE_A1", "ATTRIBUTE_Q2", "ATTRIBUTE_A2", "ATTRIBUTE_Q3", "ATTRIBUTE_A3", "ATTRIBUTE_Q4", "ATTRIBUTE_A4", "ATTRIBUTE_Q5", "ATTRIBUTE_A5", "ATTRIBUTE_Q6", "ATTRIBUTE_A6", "ATTRIBUTE_Q7", "ATTRIBUTE_A7", "ATTRIBUTE_Q8", "ATTRIBUTE_A8", "ATTRIBUTE_Q9", "ATTRIBUTE_A9", "ATTRIBUTE_Q10", "ATTRIBUTE_A10", "CONDITION_Q1", "CONDITION_A1", "CONDITION_Q2", "CONDITION_A2", "CONDITION_Q3", "CONDITION_A3", "CONDITION_Q4", "CONDITION_A4", "CONDITION_Q5", "CONDITION_A5", "CONDITION_Q6", "CONDITION_A6", "CONDITION_Q7", "CONDITION_A7", "CONDITION_Q8", "CONDITION_A8", "CONDITION_Q9", "CONDITION_A9", "CONDITION_Q10", "CONDITION_A10", "COF_REPLACEMENT_COST", "COF_OM_IMPACTS", "COF_LEVEL_OF_SERVICE", "COF_HEALTH_AND_SAFETY", "COF_PERMIT_COMPLIANCE", "COF_RESPONSE_TIME", "COF_SERVICE_PRIORITY", "FLOODING_HARVEY", "FLOODING_REPAIRS", "FLOODING_EXTENT", "FLOODING_DURATION", "FLOODING_IN_DDD", "FLOODING_UNREPORTED", "FLOODING_UNREPORTED_QUANTITY", "FLOODING_UNREPORTED_DIMENSIONS", "FLOODING_UNREPORTED_HOW", "FLOODING_UNREPORTED_REPAIRED", "FLOODING_LATENT", "FLOODING_LATENT_QUANTITY", "FLOODING_LATENT_DIMENSIONS", "FLOODING_LATENT_HOW", "FLOODING_LATENT_REPAIRED", "PHOTO", "NOTES", "DT_INSERTED") AS SELECT
        trim(asset_id),
        trim(asset_stage),
        trim(location),
        trim(location_id),
        trim(eam_location),
        trim(system),
        trim(system_id),
        trim(eam_system),
        trim(system_class_code),
        trim(position),
        trim(position_id),
        trim(position_class),
        trim(column1),
        trim(position_class_code),
        trim(eam_position),
        trim(subposition),
        trim(subposition_id),
        trim(sub_position_class),
        trim(column22),
        trim(sub_position_class_code),
        trim(eam_subposition),
        trim(asset),
        trim(asset_in_eam),
        trim(discipline),
        trim(class),
        trim(class_id),
        trim(category),
        trim(install_date),
        trim(position_commission_date),
        trim(status),
        trim(assessment_date),
        trim(operator_present),
        trim(lof_capacity),
        trim(lof_reliability),
        trim(lof_om),
        trim(lof_obsolescence),
        trim(lof_redundancy),
        trim(lof_erul),
        trim(attribute_q1),
        trim(attribute_a1),
        trim(attribute_q2),
        trim(attribute_a2),
        trim(attribute_q3),
        trim(attribute_a3),
        trim(attribute_q4),
        trim(attribute_a4),
        trim(attribute_q5),
        trim(attribute_a5),
        trim(attribute_q6),
        trim(attribute_a6),
        trim(attribute_q7),
        trim(attribute_a7),
        trim(attribute_q8),
        trim(attribute_a8),
        trim(attribute_q9),
        trim(attribute_a9),
        trim(attribute_q10),
        trim(attribute_a10),
        trim(condition_q1),
        trim(condition_a1),
        trim(condition_q2),
        trim(condition_a2),
        trim(condition_q3),
        trim(condition_a3),
        trim(condition_q4),
        trim(condition_a4),
        trim(condition_q5),
        trim(condition_a5),
        trim(condition_q6),
        trim(condition_a6),
        trim(condition_q7),
        trim(condition_a7),
        trim(condition_q8),
        trim(condition_a8),
        trim(condition_q9),
        trim(condition_a9),
        trim(condition_q10),
        trim(condition_a10),
        trim(cof_replacement_cost),
        trim(cof_om_impacts),
        trim(cof_level_of_service),
        trim(cof_health_and_safety),
        trim(cof_permit_compliance),
        trim(cof_response_time),
        trim(cof_service_priority),
        trim(flooding_harvey),
        trim(flooding_repairs),
        trim(flooding_extent),
        trim(flooding_duration),
        trim(flooding_in_ddd),
        trim(flooding_unreported),
        trim(flooding_unreported_quantity),
        trim(flooding_unreported_dimensions),
        trim(flooding_unreported_how),
        trim(flooding_unreported_repaired),
        trim(flooding_latent),
        trim(flooding_latent_quantity),
        trim(flooding_latent_dimensions),
        trim(flooding_latent_how),
        trim(flooding_latent_repaired),
        trim(photo),
        trim(notes),
       dt_inserted
    FROM
        e_wwo_raw_tab2
;
  GRANT DELETE ON "COH_DEV_E"."E_WWO_RAW_TAB2_V" TO "COH_DEV_T" WITH GRANT OPTION;
  GRANT INSERT ON "COH_DEV_E"."E_WWO_RAW_TAB2_V" TO "COH_DEV_T" WITH GRANT OPTION;
  GRANT SELECT ON "COH_DEV_E"."E_WWO_RAW_TAB2_V" TO "COH_DEV_T" WITH GRANT OPTION;
  GRANT UPDATE ON "COH_DEV_E"."E_WWO_RAW_TAB2_V" TO "COH_DEV_T" WITH GRANT OPTION;
  GRANT REFERENCES ON "COH_DEV_E"."E_WWO_RAW_TAB2_V" TO "COH_DEV_T" WITH GRANT OPTION;
  GRANT READ ON "COH_DEV_E"."E_WWO_RAW_TAB2_V" TO "COH_DEV_T" WITH GRANT OPTION;
  GRANT ON COMMIT REFRESH ON "COH_DEV_E"."E_WWO_RAW_TAB2_V" TO "COH_DEV_T" WITH GRANT OPTION;
  GRANT QUERY REWRITE ON "COH_DEV_E"."E_WWO_RAW_TAB2_V" TO "COH_DEV_T" WITH GRANT OPTION;
  GRANT DEBUG ON "COH_DEV_E"."E_WWO_RAW_TAB2_V" TO "COH_DEV_T" WITH GRANT OPTION;
  GRANT FLASHBACK ON "COH_DEV_E"."E_WWO_RAW_TAB2_V" TO "COH_DEV_T" WITH GRANT OPTION;
  GRANT MERGE VIEW ON "COH_DEV_E"."E_WWO_RAW_TAB2_V" TO "COH_DEV_T" WITH GRANT OPTION;
