--------------------------------------------------------
--  DDL for View E_WWO_CLASS_SEGMENTATION_V
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "COH_DEV_E"."E_WWO_CLASS_SEGMENTATION_V" ("DATA_UNIT", "DWO_CLASS_DESCRIPTION", "WWO_CLASS_DESCRIPTION", "DWO_CLASS_ID", "WWO_CLASS_ID", "COMMON_NEW_COMMENTS", "COMMON_CLASS_FLAG", "SEGMENTATION_COMMENTS", "DT_INSERTED") AS SELECT
        trim(data_unit),
        trim(dwo_class_description),
        trim(wwo_class_description),
        trim(dwo_class_id),
        trim(wwo_class_id),
        trim(common_new_comments),
        trim(common_class_flag),
        trim(segmentation_comments),
        dt_inserted
    FROM
        e_wwo_class_segmentation
;
  GRANT DELETE ON "COH_DEV_E"."E_WWO_CLASS_SEGMENTATION_V" TO "COH_DEV_T" WITH GRANT OPTION;
  GRANT INSERT ON "COH_DEV_E"."E_WWO_CLASS_SEGMENTATION_V" TO "COH_DEV_T" WITH GRANT OPTION;
  GRANT SELECT ON "COH_DEV_E"."E_WWO_CLASS_SEGMENTATION_V" TO "COH_DEV_T" WITH GRANT OPTION;
  GRANT UPDATE ON "COH_DEV_E"."E_WWO_CLASS_SEGMENTATION_V" TO "COH_DEV_T" WITH GRANT OPTION;
  GRANT REFERENCES ON "COH_DEV_E"."E_WWO_CLASS_SEGMENTATION_V" TO "COH_DEV_T" WITH GRANT OPTION;
  GRANT READ ON "COH_DEV_E"."E_WWO_CLASS_SEGMENTATION_V" TO "COH_DEV_T" WITH GRANT OPTION;
  GRANT ON COMMIT REFRESH ON "COH_DEV_E"."E_WWO_CLASS_SEGMENTATION_V" TO "COH_DEV_T" WITH GRANT OPTION;
  GRANT QUERY REWRITE ON "COH_DEV_E"."E_WWO_CLASS_SEGMENTATION_V" TO "COH_DEV_T" WITH GRANT OPTION;
  GRANT DEBUG ON "COH_DEV_E"."E_WWO_CLASS_SEGMENTATION_V" TO "COH_DEV_T" WITH GRANT OPTION;
  GRANT FLASHBACK ON "COH_DEV_E"."E_WWO_CLASS_SEGMENTATION_V" TO "COH_DEV_T" WITH GRANT OPTION;
  GRANT MERGE VIEW ON "COH_DEV_E"."E_WWO_CLASS_SEGMENTATION_V" TO "COH_DEV_T" WITH GRANT OPTION;
  GRANT DELETE ON "COH_DEV_E"."E_WWO_CLASS_SEGMENTATION_V" TO "COH_DEV_L" WITH GRANT OPTION;
  GRANT INSERT ON "COH_DEV_E"."E_WWO_CLASS_SEGMENTATION_V" TO "COH_DEV_L" WITH GRANT OPTION;
  GRANT SELECT ON "COH_DEV_E"."E_WWO_CLASS_SEGMENTATION_V" TO "COH_DEV_L" WITH GRANT OPTION;
  GRANT UPDATE ON "COH_DEV_E"."E_WWO_CLASS_SEGMENTATION_V" TO "COH_DEV_L" WITH GRANT OPTION;
  GRANT REFERENCES ON "COH_DEV_E"."E_WWO_CLASS_SEGMENTATION_V" TO "COH_DEV_L" WITH GRANT OPTION;
  GRANT ON COMMIT REFRESH ON "COH_DEV_E"."E_WWO_CLASS_SEGMENTATION_V" TO "COH_DEV_L" WITH GRANT OPTION;
  GRANT QUERY REWRITE ON "COH_DEV_E"."E_WWO_CLASS_SEGMENTATION_V" TO "COH_DEV_L" WITH GRANT OPTION;
  GRANT DEBUG ON "COH_DEV_E"."E_WWO_CLASS_SEGMENTATION_V" TO "COH_DEV_L" WITH GRANT OPTION;
  GRANT FLASHBACK ON "COH_DEV_E"."E_WWO_CLASS_SEGMENTATION_V" TO "COH_DEV_L" WITH GRANT OPTION;
  GRANT MERGE VIEW ON "COH_DEV_E"."E_WWO_CLASS_SEGMENTATION_V" TO "COH_DEV_L" WITH GRANT OPTION;
  GRANT READ ON "COH_DEV_E"."E_WWO_CLASS_SEGMENTATION_V" TO "COH_DEV_L" WITH GRANT OPTION;
