--------------------------------------------------------
--  DDL for Table DWO_CLASS_CONDITION_Q_MASTER
--------------------------------------------------------

  CREATE TABLE "COH_DEV_T"."DWO_CLASS_CONDITION_Q_MASTER" ("DWO_SET_NUM" NUMBER, "DWO_CLASS_DESCRIPTION" VARCHAR2(100), "DWO_CLASS_ID" VARCHAR2(10), "CONDITION_Q1" VARCHAR2(255), "CONDITION_Q2" VARCHAR2(255), "CONDITION_Q3" VARCHAR2(255), "CONDITION_Q4" VARCHAR2(255), "CONDITION_Q5" VARCHAR2(255), "CONDITION_Q6" VARCHAR2(255), "CONDITION_Q7" VARCHAR2(255), "CONDITION_Q8" VARCHAR2(255), "CONDITION_Q9" VARCHAR2(255), "CONDITION_Q10" VARCHAR2(255)) ;
  GRANT READ ON "COH_DEV_T"."DWO_CLASS_CONDITION_Q_MASTER" TO "COH_DEV_L";
