--------------------------------------------------------
--  DDL for Table LOAD_COMMON_ASSET_CLEANED_3_PERFORMANCE_INFO
--------------------------------------------------------

  CREATE TABLE "COH_DEV_T"."LOAD_COMMON_ASSET_CLEANED_3_PERFORMANCE_INFO" ("ASSET_ID" VARCHAR2(10), "PERFORMANCE_CAPACITY" VARCHAR2(200), "PERFORMANCE_RELIABILITY" VARCHAR2(200), "PERFORMANCE_OM" VARCHAR2(200), "PERFORMANCE_OBSOLESCENCE" VARCHAR2(200), "PERFORMANCE_REDUNDANCY" VARCHAR2(200), "PERFORMANCE_SCORE" NUMBER, "PERFORMANCE_RATING" VARCHAR2(20), "REDUNDANCY_FACTOR_REVISED" NUMBER, "DT_INSERTED" DATE) ;
  GRANT READ ON "COH_DEV_T"."LOAD_COMMON_ASSET_CLEANED_3_PERFORMANCE_INFO" TO "COH_DEV_L";
