--------------------------------------------------------
--  DDL for Table LOAD_UNQ_ASSET_CLEANED_4_AMC_INFO
--------------------------------------------------------

  CREATE TABLE "COH_DEV_T"."LOAD_UNQ_ASSET_CLEANED_4_AMC_INFO" ("ASSET_ID" VARCHAR2(10), "CLASS_ID" VARCHAR2(10), "CLASS_DESCRIPTION" VARCHAR2(100), "CATEGORY_ID" VARCHAR2(10), "CATEGORY_DESCRIPTION" VARCHAR2(100), "ESTIMATED_USEFUL_LIFE" NUMBER, "MIN_SYSTEM_COMMISSION_YEAR" NUMBER, "MAX_NO_OF_REHABS" NUMBER, "REHAB_REVITALIZATION_PERCENT" NUMBER, "CONDITION_SCORE" NUMBER, "AGE" NUMBER, "PERCENT_LIFE_CONSUMED_NUMBER" NUMBER, "PERCENT_LIFE_CONSUMED" NUMBER, "CONDITION_ADJUSTED_USEFUL_LIFE" NUMBER, "CONDITION_ADJUSTED_LIFE_REMAINING" NUMBER, "CONDITION_ADJUSTED_PERCENT_LIFE_CONSUMED_NUMBER" NUMBER, "CONDITION_ADJUSTED_PERCENT_LIFE_CONSUMED" NUMBER, "PREDICTED_REPLACEMENT_YEAR" NUMBER, "PREDICTED_CIP_YEAR" VARCHAR2(20), "LIFE_REMAINING" NUMBER) ;
  GRANT READ ON "COH_DEV_T"."LOAD_UNQ_ASSET_CLEANED_4_AMC_INFO" TO "COH_DEV_L";
