--------------------------------------------------------
--  DDL for Table LOAD_COMMON_ASSET_CLEANED_5_COF_INFO
--------------------------------------------------------

  CREATE TABLE "COH_DEV_T"."LOAD_COMMON_ASSET_CLEANED_5_COF_INFO" ("ASSET_ID" VARCHAR2(10), "COF_REPLACEMENT_COST" VARCHAR2(100), "COF_OM_IMPACTS" VARCHAR2(100), "COF_LEVEL_OF_SERVICE" VARCHAR2(100), "COF_HEALTH_AND_SAFETY" VARCHAR2(100), "COF_PERMIT_COMPLIANCE" VARCHAR2(100), "COF_RESPONSE_TIME" VARCHAR2(100), "COF_SERVICE_PRIORITY" VARCHAR2(100), "COF_SCORE" NUMBER, "COF_RATING" VARCHAR2(20)) ;
  GRANT READ ON "COH_DEV_T"."LOAD_COMMON_ASSET_CLEANED_5_COF_INFO" TO "COH_DEV_L";
