--------------------------------------------------------
--  DDL for Table LOAD_UNQ_ASSET_CLEANED_1_ASSET_INFO
--------------------------------------------------------

  CREATE TABLE "COH_DEV_T"."LOAD_UNQ_ASSET_CLEANED_1_ASSET_INFO" ("ASSET_ID" VARCHAR2(10), "CLASS_ID" VARCHAR2(10), "CLASS_DESCRIPTION" VARCHAR2(100), "CATEGORY_ID" VARCHAR2(10), "CATEGORY_DESCRIPTION" VARCHAR2(100), "COMMISSION_DATE" DATE, "MIN_SYSTEM_COMMISSION_YEAR" NUMBER, "ESTIMATED_USEFUL_LIFE" NUMBER, "MAX_NO_OF_REHABS" NUMBER, "REHAB_REVITALIZATION_PERCENT" NUMBER, "DT_INSERTED" DATE DEFAULT sysdate, "DU11_FLAG" CHAR(1) DEFAULT 'N') ;
  GRANT READ ON "COH_DEV_T"."LOAD_UNQ_ASSET_CLEANED_1_ASSET_INFO" TO "COH_DEV_L";
