--------------------------------------------------------
--  DDL for Table LOAD_COMMON_ASSET_CLEANED_2_CONDITION_Q_INFO
--------------------------------------------------------

  CREATE TABLE "COH_DEV_T"."LOAD_COMMON_ASSET_CLEANED_2_CONDITION_Q_INFO" ("ASSET_ID" VARCHAR2(10), "CLASS_ID" VARCHAR2(10), "CLASS_DESCRIPTION" VARCHAR2(100), "CONDITION_Q1" VARCHAR2(255), "CONDITION_A1" NUMBER(1,0), "CONDITION_Q2" VARCHAR2(255), "CONDITION_A2" NUMBER(1,0), "CONDITION_Q3" VARCHAR2(255), "CONDITION_A3" NUMBER(1,0), "CONDITION_Q4" VARCHAR2(255), "CONDITION_A4" NUMBER(1,0), "CONDITION_Q5" VARCHAR2(255), "CONDITION_A5" NUMBER(1,0), "CONDITION_Q6" VARCHAR2(255), "CONDITION_A6" NUMBER(1,0), "CONDITION_Q7" VARCHAR2(255), "CONDITION_A7" NUMBER(1,0), "CONDITION_Q8" VARCHAR2(255), "CONDITION_A8" NUMBER(1,0), "CONDITION_Q9" VARCHAR2(255), "CONDITION_A9" NUMBER(1,0), "CONDITION_Q10" VARCHAR2(255), "CONDITION_A10" NUMBER(1,0), "CONDITION_SCORE" NUMBER(1,0), "CONDITION_RATING" VARCHAR2(20), "DT_INSERTED" DATE) ;
  GRANT READ ON "COH_DEV_T"."LOAD_COMMON_ASSET_CLEANED_2_CONDITION_Q_INFO" TO "COH_DEV_L";
