--------------------------------------------------------
--  DDL for Table LOAD_COMMON_ASSET_CLEANED_6_PERF_COND_LOF_INFO
--------------------------------------------------------

  CREATE TABLE "COH_DEV_T"."LOAD_COMMON_ASSET_CLEANED_6_PERF_COND_LOF_INFO" ("ASSET_ID" VARCHAR2(10), "PERFORMANCE_SCORE" NUMBER, "CONDITION_SCORE" NUMBER, "LOF_SCORE" NUMBER, "LOF_RATING" VARCHAR2(20), "DT_INSERTED" DATE) ;
  GRANT READ ON "COH_DEV_T"."LOAD_COMMON_ASSET_CLEANED_6_PERF_COND_LOF_INFO" TO "COH_DEV_L";
