--------------------------------------------------------
--  DDL for Table T_OUT_ALL_ASSET_CLASS_SEGMENTATION
--------------------------------------------------------

  CREATE TABLE "COH_DEV_T"."T_OUT_ALL_ASSET_CLASS_SEGMENTATION" ("DATA_UNIT" NUMBER, "WWO_CLASS_ID" VARCHAR2(20), "WWO_CLASS_DESCRIPTION" VARCHAR2(100), "UNQ_RAW_ASSET_COUNT" NUMBER, "UNQ_EAM_ASSET_COUNT" NUMBER, "COMMON_RAW_ASSET_COUNT" NUMBER, "COMMON_EAM_ASSET_COUNT" NUMBER, "TOTAL_RAW_ASSET_COUNT" NUMBER, "TOTAL_EAM_ASSET_COUNT" NUMBER, "CLASS_TYPE" VARCHAR2(7), "DT_INSERTED" DATE DEFAULT sysdate) ;
  GRANT ALTER ON "COH_DEV_T"."T_OUT_ALL_ASSET_CLASS_SEGMENTATION" TO "COH_DEV_L";
  GRANT DELETE ON "COH_DEV_T"."T_OUT_ALL_ASSET_CLASS_SEGMENTATION" TO "COH_DEV_L";
  GRANT INDEX ON "COH_DEV_T"."T_OUT_ALL_ASSET_CLASS_SEGMENTATION" TO "COH_DEV_L";
  GRANT INSERT ON "COH_DEV_T"."T_OUT_ALL_ASSET_CLASS_SEGMENTATION" TO "COH_DEV_L";
  GRANT SELECT ON "COH_DEV_T"."T_OUT_ALL_ASSET_CLASS_SEGMENTATION" TO "COH_DEV_L";
  GRANT UPDATE ON "COH_DEV_T"."T_OUT_ALL_ASSET_CLASS_SEGMENTATION" TO "COH_DEV_L";
  GRANT REFERENCES ON "COH_DEV_T"."T_OUT_ALL_ASSET_CLASS_SEGMENTATION" TO "COH_DEV_L";
  GRANT READ ON "COH_DEV_T"."T_OUT_ALL_ASSET_CLASS_SEGMENTATION" TO "COH_DEV_L";
  GRANT ON COMMIT REFRESH ON "COH_DEV_T"."T_OUT_ALL_ASSET_CLASS_SEGMENTATION" TO "COH_DEV_L";
  GRANT QUERY REWRITE ON "COH_DEV_T"."T_OUT_ALL_ASSET_CLASS_SEGMENTATION" TO "COH_DEV_L";
  GRANT DEBUG ON "COH_DEV_T"."T_OUT_ALL_ASSET_CLASS_SEGMENTATION" TO "COH_DEV_L";
  GRANT FLASHBACK ON "COH_DEV_T"."T_OUT_ALL_ASSET_CLASS_SEGMENTATION" TO "COH_DEV_L";
