--------------------------------------------------------
--  DDL for Table WWO_COMMON_ASSET_CLEANED_NO_CALC_CONDITION_Q
--------------------------------------------------------

  CREATE TABLE "COH_DEV_T"."WWO_COMMON_ASSET_CLEANED_NO_CALC_CONDITION_Q" ("ASSET_ID" VARCHAR2(10), "CLASS_ID" VARCHAR2(10), "CLASS_DESCRIPTION" VARCHAR2(20), "RAW_CONDITION_Q_NO" VARCHAR2(13), "RAW_CONDITION_Q" VARCHAR2(255), "RAW_CONDITION_A_NO" VARCHAR2(13), "RAW_CONDITION_A" VARCHAR2(255), "SRC" VARCHAR2(20), "RAW_CONDITION_Q_ID" NUMBER, "FINAL_REF_CONDITION_Q_ID" VARCHAR2(100), "FINAL_REF_CONDITION_Q_NO" VARCHAR2(100), "FINAL_REF_CONDITION_Q" VARCHAR2(255), "MATCH_COMMENTS" VARCHAR2(4000) DEFAULT NULL, "FINAL_CONDITION_A" VARCHAR2(20)) ;
