--------------------------------------------------------
--  DDL for Table WWO_COMMON_ASSET_CLEANED_NO_CALC_CONDITION_Q_T
--------------------------------------------------------

  CREATE TABLE "COH_DEV_T"."WWO_COMMON_ASSET_CLEANED_NO_CALC_CONDITION_Q_T" ("ASSET_ID" VARCHAR2(10), "CLASS_ID" VARCHAR2(10), "CLASS_DESCRIPTION" VARCHAR2(20), "CONDITION_Q1" VARCHAR2(255), "CONDITION_A1" VARCHAR2(5), "CONDITION_Q2" VARCHAR2(255), "CONDITION_A2" VARCHAR2(5), "CONDITION_Q3" VARCHAR2(255), "CONDITION_A3" VARCHAR2(5), "CONDITION_Q4" VARCHAR2(255), "CONDITION_A4" VARCHAR2(5), "CONDITION_Q5" VARCHAR2(255), "CONDITION_A5" VARCHAR2(5), "CONDITION_Q6" VARCHAR2(255), "CONDITION_A6" VARCHAR2(5), "CONDITION_Q7" VARCHAR2(255), "CONDITION_A7" VARCHAR2(5), "CONDITION_Q8" VARCHAR2(255), "CONDITION_A8" VARCHAR2(5), "CONDITION_Q9" VARCHAR2(255), "CONDITION_A9" VARCHAR2(5), "CONDITION_Q10" VARCHAR2(255), "CONDITION_A10" VARCHAR2(5), "SRC" VARCHAR2(10)) ;
