--------------------------------------------------------
--  DDL for Table WWO_COMMON_ASSET_CONDITION_SET_Q_MASTER_KEY
--------------------------------------------------------

  CREATE TABLE "COH_DEV_T"."WWO_COMMON_ASSET_CONDITION_SET_Q_MASTER_KEY" ("RAW_CONDITION_Q_ID" NUMBER, "CLASS_ID" VARCHAR2(10), "CLASS_DESCRIPTION" VARCHAR2(20), "RAW_CONDITION_Q_NO" VARCHAR2(13), "RAW_CONDITION_Q" VARCHAR2(255), "SRC" VARCHAR2(10)) ;
