--------------------------------------------------------
--  DDL for Table WWO_CONDITION_SET_Q_MASTER
--------------------------------------------------------

  CREATE TABLE "COH_DEV_T"."WWO_CONDITION_SET_Q_MASTER" ("ORGANIZATION" VARCHAR2(10), "CLASS_ID" VARCHAR2(10), "CLASS_DESCRIPTION" VARCHAR2(20), "CONDITION_Q1" VARCHAR2(255), "CONDITION_Q2" VARCHAR2(255), "CONDITION_Q3" VARCHAR2(255), "CONDITION_Q4" VARCHAR2(255), "CONDITION_Q5" VARCHAR2(255), "CONDITION_Q6" VARCHAR2(255), "CONDITION_Q7" VARCHAR2(255), "CONDITION_Q8" VARCHAR2(255), "CONDITION_Q9" VARCHAR2(255), "CONDITION_Q10" VARCHAR2(255), "COMMENTS" VARCHAR2(200), "MATCHING_WITH_DWO" CHAR(1)) ;
  GRANT READ ON "COH_DEV_T"."WWO_CONDITION_SET_Q_MASTER" TO "COH_DEV_L";
