--------------------------------------------------------
--  DDL for Table WWO_SEGMNT_UNQ_ASSET_CLASS_MASTER
--------------------------------------------------------

  CREATE TABLE "COH_DEV_T"."WWO_SEGMNT_UNQ_ASSET_CLASS_MASTER" ("DATA_UNIT" NUMBER, "DWO_CLASS_ID" VARCHAR2(10), "DWO_CLASS_DESCRIPTION" VARCHAR2(20), "WWO_CLASS_ID" VARCHAR2(10), "WWO_CLASS_DESCRIPTION" VARCHAR2(20), "COMMON_CLASS_FLAG" CHAR(1), "RAW_DATA_UNIQUE_ASSET_COUNT" NUMBER, "EAM_DATA_UNIQUE_ASSET_COUNT" NUMBER, "COMMON_NEW_COMMENTS" VARCHAR2(1000), "SEGMENTATION_COMMENTS" VARCHAR2(500), "DT_INSERTED" DATE DEFAULT sysdate) ;
  GRANT READ ON "COH_DEV_T"."WWO_SEGMNT_UNQ_ASSET_CLASS_MASTER" TO "COH_DEV_L";
