--------------------------------------------------------
--  DDL for Table WWO_ASSET_TYPES_MASTER
--------------------------------------------------------

  CREATE TABLE "COH_DEV_T"."WWO_ASSET_TYPES_MASTER" ("CLASS_ID" VARCHAR2(10), "CLASS_DESCRIPTION" VARCHAR2(100), "CATEGORY_ID" VARCHAR2(10), "CATEGORY_DESCRIPTION" VARCHAR2(100), "ESTIMATED_USEFUL_LIFE" NUMBER DEFAULT NULL, "MAX_NO_OF_REHABS" NUMBER DEFAULT NULL, "REHAB_REVITALIZATION" NUMBER DEFAULT NULL, "INITIAL_REINVESTMENT_ACTION" VARCHAR2(20), "REHAB_EUL" NUMBER DEFAULT NULL, "MAX_POTENTIAL_LIFE" NUMBER DEFAULT NULL, "CIP_RECOMMENDED_REINVESTMENT_ACTION" VARCHAR2(20), "DU11_FLAG" CHAR(1) DEFAULT 'N') ;
  GRANT READ ON "COH_DEV_T"."WWO_ASSET_TYPES_MASTER" TO "COH_DEV_L";
