--------------------------------------------------------
--  DDL for Table WWO_CONDITION_SET_Q_MASTER_TRANSPOSE
--------------------------------------------------------

  CREATE TABLE "COH_DEV_T"."WWO_CONDITION_SET_Q_MASTER_TRANSPOSE" ("ORGANIZATION" VARCHAR2(20), "CLASS_ID" VARCHAR2(10), "CLASS_DESCRIPTION" VARCHAR2(20), "MATCHING_WITH_DWO" CHAR(1), "REF_CONDITION_Q_NO" VARCHAR2(13), "REF_CONDITION_Q" VARCHAR2(255), "REF_CONDITION_Q_ID" NUMBER) ;
  GRANT READ ON "COH_DEV_T"."WWO_CONDITION_SET_Q_MASTER_TRANSPOSE" TO "COH_DEV_QA";
