--------------------------------------------------------
--  DDL for Table WWO_COST_OVERRIDE_MASTER
--------------------------------------------------------

  CREATE TABLE "COH_DEV_T"."WWO_COST_OVERRIDE_MASTER" ("CLASS_ID" VARCHAR2(10), "CLASS_DESCRIPTION" VARCHAR2(20), "CATEGORY_ID" VARCHAR2(10), "CATEGORY_DESCRIPTION" VARCHAR2(50), "REHAB_REPLACEMENT" VARCHAR2(20), "LABOR" NUMBER, "EQUIPMENT_COST" NUMBER, "GENERAL_CONDITION_5_PERCENT" NUMBER, "CONTRACT_OH_N_PROFIT_15_PERCENT" NUMBER, "ENG_CM_ADMIN_LEGAL_20_PERCENT" NUMBER, "SUB_TOTAL" NUMBER, "CONTIGENCY_25_PERCENT" NUMBER, "TOTAL_COST" NUMBER, "COST_OVERRIDE" NUMBER, "DU11_FLAG" CHAR(1) DEFAULT 'N') ;
  GRANT READ ON "COH_DEV_T"."WWO_COST_OVERRIDE_MASTER" TO "COH_DEV_L";
