--------------------------------------------------------
--  DDL for Table WWO_UNQ_ASSET_CLEANED_NO_CALC_CONDITION_Q
--------------------------------------------------------

  CREATE TABLE "COH_DEV_T"."WWO_UNQ_ASSET_CLEANED_NO_CALC_CONDITION_Q" ("ASSET_ID" VARCHAR2(10), "CLASS_ID" VARCHAR2(10), "CLASS_DESCRIPTION" VARCHAR2(20), "RAW_CONDITION_Q_NO" VARCHAR2(13), "RAW_CONDITION_Q" VARCHAR2(200), "RAW_CONDITION_A_NO" VARCHAR2(13), "RAW_CONDITION_A" VARCHAR2(10), "RAW_CONDITION_Q_ID" NUMBER, "FINAL_REF_CONDITION_Q_ID" VARCHAR2(200), "FINAL_REF_CONDITION_Q_NO" VARCHAR2(200), "FINAL_REF_CONDITION_Q" VARCHAR2(200), "MATCH_COMMENTS" VARCHAR2(1000) DEFAULT NULL, "FINAL_CONDITION_A" VARCHAR2(5)) ;
  GRANT ALTER ON "COH_DEV_T"."WWO_UNQ_ASSET_CLEANED_NO_CALC_CONDITION_Q" TO "COH_DEV_L";
  GRANT DELETE ON "COH_DEV_T"."WWO_UNQ_ASSET_CLEANED_NO_CALC_CONDITION_Q" TO "COH_DEV_L";
  GRANT INDEX ON "COH_DEV_T"."WWO_UNQ_ASSET_CLEANED_NO_CALC_CONDITION_Q" TO "COH_DEV_L";
  GRANT INSERT ON "COH_DEV_T"."WWO_UNQ_ASSET_CLEANED_NO_CALC_CONDITION_Q" TO "COH_DEV_L";
  GRANT SELECT ON "COH_DEV_T"."WWO_UNQ_ASSET_CLEANED_NO_CALC_CONDITION_Q" TO "COH_DEV_L";
  GRANT UPDATE ON "COH_DEV_T"."WWO_UNQ_ASSET_CLEANED_NO_CALC_CONDITION_Q" TO "COH_DEV_L";
  GRANT REFERENCES ON "COH_DEV_T"."WWO_UNQ_ASSET_CLEANED_NO_CALC_CONDITION_Q" TO "COH_DEV_L";
  GRANT READ ON "COH_DEV_T"."WWO_UNQ_ASSET_CLEANED_NO_CALC_CONDITION_Q" TO "COH_DEV_L";
  GRANT ON COMMIT REFRESH ON "COH_DEV_T"."WWO_UNQ_ASSET_CLEANED_NO_CALC_CONDITION_Q" TO "COH_DEV_L";
  GRANT QUERY REWRITE ON "COH_DEV_T"."WWO_UNQ_ASSET_CLEANED_NO_CALC_CONDITION_Q" TO "COH_DEV_L";
  GRANT DEBUG ON "COH_DEV_T"."WWO_UNQ_ASSET_CLEANED_NO_CALC_CONDITION_Q" TO "COH_DEV_L";
  GRANT FLASHBACK ON "COH_DEV_T"."WWO_UNQ_ASSET_CLEANED_NO_CALC_CONDITION_Q" TO "COH_DEV_L";
