--------------------------------------------------------
--  DDL for Table TEMPLATE_ASSET_TYPES
--------------------------------------------------------

  CREATE TABLE "COH_DEV_QA"."TEMPLATE_ASSET_TYPES" ("CLASS_CODE_REVISED" VARCHAR2(100), "CLASS_DESCRIPTION_REVISED" VARCHAR2(100), "CATEGORY_CODE_REVISED" VARCHAR2(100), "CATEGORY_DESCRIPTION_REVISED" VARCHAR2(100), "ESTIMATED_USEFUL_LIFE_EUL" NUMBER, "INITIAL_REINVESTMENT_ACTION" VARCHAR2(200), "MAX_NO_OF_REHABS" NUMBER, "REHAB_REVITALIZATION" NUMBER, "REHAB_EUL" NUMBER, "MAX_POTENTIAL_LIFE" NUMBER) ;
