--------------------------------------------------------
--  DDL for Table TEMPLATE_COST_OVERRIDE
--------------------------------------------------------

  CREATE TABLE "COH_DEV_QA"."TEMPLATE_COST_OVERRIDE" ("CLASS_CODE_REVISED" VARCHAR2(1000), "CLASS_DESCRIPTION_REVISED" VARCHAR2(1000), "CATEGORY_CODE_REVISED" VARCHAR2(1000), "CATEGORY_DESCRIPTION_REVISED" VARCHAR2(1000), "REHAB_REPLACEMENT" VARCHAR2(1000), "LABOR" NUMBER, "EQUIPMENT_COST" NUMBER, "GENERAL_CONDITION_5_PERCENT" NUMBER, "CONTRACT_OH_N_PROFIT_15_PERCENT" NUMBER, "ENG_CM_ADMIN_LEGAL_20_PERCENT" NUMBER, "SUB_TOTAL" NUMBER, "CONTIGENCY_25_PERCENT" NUMBER, "TOTAL_COST" NUMBER) ;
