--------------------------------------------------------
--  DDL for Table TEST_COND_Q_2
--------------------------------------------------------

  CREATE TABLE "COH_DEV_QA"."TEST_COND_Q_2" ("DATA_UNIT" VARCHAR2(4000), "CLASS_ID" VARCHAR2(4000), "CLASS_DESCRIPTION" VARCHAR2(4000), "RAW_CONDITION_Q_NO" VARCHAR2(4000), "RAW_CONDITION_Q" VARCHAR2(4000), "KEYWORD_1" VARCHAR2(4000), "KEYWORD_2" VARCHAR2(4000), "REF_CONDITION_Q_NO" VARCHAR2(13), "REF_CONDITION_Q" VARCHAR2(4000), "KEYWORD_1_MATCH" CHAR(1), "COLUMN2KEYWORD_2_MATCH" CHAR(1)) ;
