--------------------------------------------------------
--  File created - Monday-December-02-2024   
--------------------------------------------------------
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_e\TABLES\E_BASINDRIVE_2_BASIN.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_e\TABLES\E_CLASS_DESCRIPTION.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_e\TABLES\E_DU_11_ASSETS.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_e\TABLES\E_DU_9_10_CLASS_CATEGORY_INFO.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_e\TABLES\E_DWO_CONDITION_Q_CLASS_SET.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_e\TABLES\E_DWO_CONDITION_SET_Q.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_e\TABLES\E_WWO_ASSET_TYPES.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_e\TABLES\E_WWO_CLASS_SEGMENTATION.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_e\TABLES\E_WWO_COMMON_ASSET_ACCEPT.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_e\TABLES\E_WWO_CONDITION_Q_SOLUTION.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_e\TABLES\E_WWO_CONDITION_SET_Q.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_e\TABLES\E_WWO_COST_OVERRIDE.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_e\TABLES\E_WWO_EAM_SYSTEM_EXTRACT.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_e\TABLES\E_WWO_MATRIX_ANSWERS.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_e\TABLES\E_WWO_RAW_TAB1.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_e\TABLES\E_WWO_RAW_TAB2.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_e\VIEWS\ERR_E_WWO_ASSET_TYPES_V.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_e\VIEWS\ERR_E_WWO_CLASS_SEGMENTATION_V.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_e\VIEWS\ERR_E_WWO_CONDITION_SET_Q_V.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_e\VIEWS\ERR_E_WWO_COST_OVERRIDE_V.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_e\VIEWS\E_CLASS_DESCRIPTION_V.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_e\VIEWS\E_DU_11_ASSETS_V.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_e\VIEWS\E_DU_9_10_CLASS_CATEGORY_INFO_V.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_e\VIEWS\E_DWO_CONDITION_Q_CLASS_SET_V.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_e\VIEWS\E_DWO_CONDITION_SET_Q_V.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_e\VIEWS\E_TABLE_COUNT_V.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_e\VIEWS\E_WWO_ASSET_TYPES_V.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_e\VIEWS\E_WWO_CLASS_SEGMENTATION_V.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_e\VIEWS\E_WWO_COMMON_ASSET_ACCEPT_V.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_e\VIEWS\E_WWO_CONDITION_Q_SOLUTION_V.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_e\VIEWS\E_WWO_CONDITION_SET_Q_V.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_e\VIEWS\E_WWO_COST_OVERRIDE_V.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_e\VIEWS\E_WWO_EAM_SYSTEM_EXTRACT_V.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_e\VIEWS\E_WWO_MATRIX_ANSWERS_V.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_e\VIEWS\E_WWO_RAW_TAB1_V.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_e\VIEWS\E_WWO_RAW_TAB2_V.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_e\CONSTRAINTS\E_WWO_EAM_SYSTEM_EXTRACT.sql
