--------------------------------------------------------
--  DDL for Table E_CLASS_DESCRIPTION
--------------------------------------------------------

  CREATE TABLE "COH_DEV_E"."E_CLASS_DESCRIPTION" ("CLASS_ID" VARCHAR2(10), "CLASS_DESCRIPTION" VARCHAR2(100), "ORGANIZATION" VARCHAR2(10), "DT_INSERTED" DATE DEFAULT sysdate) ;
  GRANT ALTER ON "COH_DEV_E"."E_CLASS_DESCRIPTION" TO "COH_DEV_T";
  GRANT DELETE ON "COH_DEV_E"."E_CLASS_DESCRIPTION" TO "COH_DEV_T";
  GRANT INDEX ON "COH_DEV_E"."E_CLASS_DESCRIPTION" TO "COH_DEV_T";
  GRANT INSERT ON "COH_DEV_E"."E_CLASS_DESCRIPTION" TO "COH_DEV_T";
  GRANT SELECT ON "COH_DEV_E"."E_CLASS_DESCRIPTION" TO "COH_DEV_T";
  GRANT UPDATE ON "COH_DEV_E"."E_CLASS_DESCRIPTION" TO "COH_DEV_T";
  GRANT REFERENCES ON "COH_DEV_E"."E_CLASS_DESCRIPTION" TO "COH_DEV_T";
  GRANT READ ON "COH_DEV_E"."E_CLASS_DESCRIPTION" TO "COH_DEV_T" WITH GRANT OPTION;
  GRANT ON COMMIT REFRESH ON "COH_DEV_E"."E_CLASS_DESCRIPTION" TO "COH_DEV_T";
  GRANT QUERY REWRITE ON "COH_DEV_E"."E_CLASS_DESCRIPTION" TO "COH_DEV_T";
  GRANT DEBUG ON "COH_DEV_E"."E_CLASS_DESCRIPTION" TO "COH_DEV_T";
  GRANT FLASHBACK ON "COH_DEV_E"."E_CLASS_DESCRIPTION" TO "COH_DEV_T";
