--------------------------------------------------------
--  DDL for Table E_DWO_CONDITION_SET_Q
--------------------------------------------------------

  CREATE TABLE "COH_DEV_E"."E_DWO_CONDITION_SET_Q" ("SET_NUM" NUMBER, "CONDITION_Q1" VARCHAR2(255), "CONDITION_Q2" VARCHAR2(255), "CONDITION_Q3" VARCHAR2(255), "CONDITION_Q4" VARCHAR2(255), "CONDITION_Q5" VARCHAR2(255), "CONDITION_Q6" VARCHAR2(255), "CONDITION_Q7" VARCHAR2(255), "CONDITION_Q8" VARCHAR2(255), "CONDITION_Q9" VARCHAR2(255), "CONDITION_Q10" VARCHAR2(255), "DT_INSERTED" DATE DEFAULT sysdate) ;
  GRANT READ ON "COH_DEV_E"."E_DWO_CONDITION_SET_Q" TO "COH_DEV_T" WITH GRANT OPTION;
