--------------------------------------------------------
--  DDL for Table E_WWO_ASSET_TYPES
--------------------------------------------------------

  CREATE TABLE "COH_DEV_E"."E_WWO_ASSET_TYPES" ("CLASS_ID" VARCHAR2(10), "CLASS_DESCRIPTION" VARCHAR2(100), "CATEGORY_ID" VARCHAR2(10), "CATEGORY_DESCRIPTION" VARCHAR2(100), "ESTIMATED_USEFUL_LIFE" VARCHAR2(10), "MAX_NO_OF_REHABS" VARCHAR2(10), "REHAB_REVITALIZATION" VARCHAR2(10), "DT_INSERTED" DATE DEFAULT Sysdate) ;
