--------------------------------------------------------
--  DDL for Table E_WWO_EAM_SYSTEM_EXTRACT
--------------------------------------------------------

  CREATE TABLE "COH_DEV_E"."E_WWO_EAM_SYSTEM_EXTRACT" ("ASSET" VARCHAR2(10), "DESCRIPTION" VARCHAR2(100), "ORGANIZATION" VARCHAR2(10), "STATUS" VARCHAR2(10), "DEPARTMENT" VARCHAR2(10), "CLASS" VARCHAR2(10), "CATEGORY" VARCHAR2(10), "COMMISSION_DATE" VARCHAR2(10), "OUT_OF_SERVICE" VARCHAR2(10), "ASSIGNED_TO" VARCHAR2(10), "PRODUCTION" VARCHAR2(10), "DT_INSERTED" VARCHAR2(20) DEFAULT sysdate) ;
  GRANT ALTER ON "COH_DEV_E"."E_WWO_EAM_SYSTEM_EXTRACT" TO "COH_DEV_T";
  GRANT DELETE ON "COH_DEV_E"."E_WWO_EAM_SYSTEM_EXTRACT" TO "COH_DEV_T";
  GRANT INDEX ON "COH_DEV_E"."E_WWO_EAM_SYSTEM_EXTRACT" TO "COH_DEV_T";
  GRANT INSERT ON "COH_DEV_E"."E_WWO_EAM_SYSTEM_EXTRACT" TO "COH_DEV_T";
  GRANT SELECT ON "COH_DEV_E"."E_WWO_EAM_SYSTEM_EXTRACT" TO "COH_DEV_T";
  GRANT UPDATE ON "COH_DEV_E"."E_WWO_EAM_SYSTEM_EXTRACT" TO "COH_DEV_T";
  GRANT REFERENCES ON "COH_DEV_E"."E_WWO_EAM_SYSTEM_EXTRACT" TO "COH_DEV_T";
  GRANT READ ON "COH_DEV_E"."E_WWO_EAM_SYSTEM_EXTRACT" TO "COH_DEV_T" WITH GRANT OPTION;
  GRANT ON COMMIT REFRESH ON "COH_DEV_E"."E_WWO_EAM_SYSTEM_EXTRACT" TO "COH_DEV_T";
  GRANT QUERY REWRITE ON "COH_DEV_E"."E_WWO_EAM_SYSTEM_EXTRACT" TO "COH_DEV_T";
  GRANT DEBUG ON "COH_DEV_E"."E_WWO_EAM_SYSTEM_EXTRACT" TO "COH_DEV_T";
  GRANT FLASHBACK ON "COH_DEV_E"."E_WWO_EAM_SYSTEM_EXTRACT" TO "COH_DEV_T";
