--------------------------------------------------------
--  DDL for Table E_WWO_CONDITION_Q_SOLUTION
--------------------------------------------------------

  CREATE TABLE "COH_DEV_E"."E_WWO_CONDITION_Q_SOLUTION" ("DATA_UNIT" VARCHAR2(10), "CLASS_ID" VARCHAR2(100), "CLASS_DESCRIPTION" VARCHAR2(100), "RAW_CONDITION_Q_NO" VARCHAR2(100), "RAW_CONDITION_Q" VARCHAR2(255), "REF_CONDITION_Q_NO" VARCHAR2(100), "REF_CONDITION_Q" VARCHAR2(255), "PROCEED" VARCHAR2(10)) ;
