--------------------------------------------------------
--  DDL for View T_IN_DWO_CONDITION_SET_Q_V
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "COH_DEV_T"."T_IN_DWO_CONDITION_SET_Q_V" ("SET_NUM", "CONDITION_Q1", "CONDITION_Q2", "CONDITION_Q3", "CONDITION_Q4", "CONDITION_Q5", "CONDITION_Q6", "CONDITION_Q7", "CONDITION_Q8", "CONDITION_Q9", "CONDITION_Q10", "DT_INSERTED") AS select "SET_NUM","CONDITION_Q1","CONDITION_Q2","CONDITION_Q3","CONDITION_Q4","CONDITION_Q5","CONDITION_Q6","CONDITION_Q7","CONDITION_Q8","CONDITION_Q9","CONDITION_Q10","DT_INSERTED" from coh_dev_e.E_DWO_CONDITION_SET_Q
;
  GRANT READ ON "COH_DEV_T"."T_IN_DWO_CONDITION_SET_Q_V" TO "COH_DEV_L";
