--------------------------------------------------------
--  DDL for View T_IN_WWO_CONDITION_SET_Q_V
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "COH_DEV_T"."T_IN_WWO_CONDITION_SET_Q_V" ("ORGANIZATION", "CLASS_ID", "CLASS_DESCRIPTION", "CONDITION_Q1", "CONDITION_Q2", "CONDITION_Q3", "CONDITION_Q4", "CONDITION_Q5", "CONDITION_Q6", "CONDITION_Q7", "CONDITION_Q8", "CONDITION_Q9", "CONDITION_Q10", "COMMENTS", "MATCHING_WITH_DWO") AS select "ORGANIZATION","CLASS_ID","CLASS_DESCRIPTION","CONDITION_Q1","CONDITION_Q2","CONDITION_Q3","CONDITION_Q4","CONDITION_Q5","CONDITION_Q6","CONDITION_Q7","CONDITION_Q8","CONDITION_Q9","CONDITION_Q10","COMMENTS","MATCHING_WITH_DWO" from coh_dev_e.E_WWO_CONDITION_SET_Q_v
;
