--------------------------------------------------------
--  File created - Monday-December-02-2024   
--------------------------------------------------------
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\TABLES\ACTIVE_CLASS.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\TABLES\ACTIVE_CLASS_CMN_DU_9_10.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\TABLES\ACTIVE_CLASS_COMMON.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\TABLES\ACTIVE_CLASS_CONDITION_Q.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\TABLES\ACTIVE_CLASS_DU_9_10.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\TABLES\BASIN_CLASS.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\TABLES\DU_9_10_ASSETS.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\TABLES\SNP_EXTRACT_ASSET_REGISTER_DU_9_10.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\TABLES\SNP_EXTRACT_ASSET_REGISTER_VALUES_DU_9_10.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\TABLES\SNP_EXTRACT_ASSET_TYPES_DU_9_10.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\TABLES\SNP_EXTRACT_ASSET_TYPES_VALUES_DU_9_10.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\TABLES\SNP_EXTRACT_CMN_ASSET_REGISTER_DU_9_10.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\TABLES\SNP_EXTRACT_CMN_ASSET_REGISTER_VALUES_DU_9_10.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\TABLES\SNP_EXTRACT_COST_OVERRIDE_DU_9_10.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\TABLES\SNP_EXTRACT_COST_OVERRIDE_VALUES_DU_9_10.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\CHK_ERR_CONDITION_Q.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\COMMON_ASSET_CLEANED_NO_CALC.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\COMMON_ASSET_CONDITION_Q_DISCREPENCY.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\COMMON_ASSET_PARKED.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\CONDITION_Q_CMN_ASSET_DU_9_10.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\CONDITION_Q_UNQ_ASSET_DU_9_10.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\DISCARDED_RECORDS_TAB1.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\DISCARDED_RECORDS_TAB2.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\DWO_WWO_ALL_ASSET_CONDITION_Q_COMPARISION.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\DWO_WWO_COMMON_ASSET_CONDITION_Q_COMPARISION.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\DWO_WWO_UNQ_ASSET_CONDITION_Q_COMPARISION.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\EAM_SYSTEM_EXTRACT_MASTER_FOR_ACTIVE_CLASS.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\EXTRACT_ASSET_REGISTER.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\EXTRACT_ASSET_REGISTER_DU_11.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\EXTRACT_ASSET_REGISTER_DU_9_10.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\EXTRACT_ASSET_REGISTER_VALUES.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\EXTRACT_ASSET_REGISTER_VALUES_DU_11.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\EXTRACT_ASSET_REGISTER_VALUES_DU_9_10.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\EXTRACT_ASSET_TYPES.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\EXTRACT_ASSET_TYPES_DU_11.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\EXTRACT_ASSET_TYPES_DU_9_10.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\EXTRACT_ASSET_TYPES_VALUES.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\EXTRACT_ASSET_TYPES_VALUES_DU_11.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\EXTRACT_ASSET_TYPES_VALUES_DU_9_10.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\EXTRACT_CMN_ASSET_REGISTER.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\EXTRACT_CMN_ASSET_REGISTER_VALUES.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\EXTRACT_COMMON_ASSET_REGISTER_DU_11.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\EXTRACT_COMMON_ASSET_REGISTER_DU_9_10.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\EXTRACT_COMMON_ASSET_REGISTER_VALUES_DU_11.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\EXTRACT_COMMON_ASSET_REGISTER_VALUES_DU_9_10.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\EXTRACT_COMMON_ASSET_TYPES_DU_11.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\EXTRACT_COMMON_ASSET_TYPES_DU_9_10.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\EXTRACT_COMMON_ASSET_TYPES_VALUES_DU_11.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\EXTRACT_COMMON_ASSET_TYPES_VALUES_DU_9_10.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\EXTRACT_COMMON_COST_OVERRIDE_DU_11.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\EXTRACT_COMMON_COST_OVERRIDE_DU_9_10.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\EXTRACT_COMMON_COST_OVERRIDE_VALUES_DU_11.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\EXTRACT_COMMON_COST_OVERRIDE_VALUES_DU_9_10.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\EXTRACT_COST_OVERRIDE.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\EXTRACT_COST_OVERRIDE_DU_11.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\EXTRACT_COST_OVERRIDE_DU_9_10.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\EXTRACT_COST_OVERRIDE_VALUES.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\EXTRACT_COST_OVERRIDE_VALUES_DU_11.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\EXTRACT_COST_OVERRIDE_VALUES_DU_9_10.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\PROGRESS_REPORT.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\SEGMENTATION_ALL.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\SEGMENTATION_BY_CLASS.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\SEGMENTATION_BY_DATA_UNIT.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\TEMPLATE_ASSET_REGISTER.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\TEMPLATE_ASSET_REGISTER_DU_11.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\TEMPLATE_ASSET_REGISTER_DU_9_10.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\TEMPLATE_ASSET_TYPES.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\TEMPLATE_ASSET_TYPES_DU_11.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\TEMPLATE_ASSET_TYPES_DU_9_10.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\TEMPLATE_COMMON_ASSET_REGISTER_DU_11.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\TEMPLATE_COMMON_ASSET_REGISTER_DU_9_10.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\TEMPLATE_COMMON_ASSET_TYPES_DU_11.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\TEMPLATE_COMMON_ASSET_TYPES_DU_9_10.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\TEMPLATE_COMMON_COST_OVERRIDE_DU_11.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\TEMPLATE_COMMON_COST_OVERRIDE_DU_9_10.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\TEMPLATE_COST_OVERRIDE.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\TEMPLATE_COST_OVERRIDE_DU_11.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\TEMPLATE_COST_OVERRIDE_DU_9_10.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\UNQ_ASSET_CLEANED_NO_CALC.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\UNQ_ASSET_CLEANED_NO_CALC_BY_ACTIVE_CLASS.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\UNQ_ASSET_CLEANED_NO_CALC_CONDITION_Q_BY_ACT_CLASS.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\UNQ_ASSET_CONDITION_Q_DISCREPENCY.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\UNQ_ASSET_CONDITION_Q_MAP_BY_ACTIVE_CLASS.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\UNQ_ASSET_PARKED.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\VIEWS\WORKABLE_DU.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\CONSTRAINTS\SNP_EXTRACT_ASSET_REGISTER_DU_9_10.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\CONSTRAINTS\SNP_EXTRACT_ASSET_REGISTER_VALUES_DU_9_10.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\CONSTRAINTS\SNP_EXTRACT_CMN_ASSET_REGISTER_DU_9_10.sql
@C:\Adsoleil\Github\ora_sql\coh_dev_etl\coh_dev_l\CONSTRAINTS\SNP_EXTRACT_CMN_ASSET_REGISTER_VALUES_DU_9_10.sql
