--------------------------------------------------------
--  DDL for View CONDITION_Q_UNQ_ASSET_DU_9_10
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE VIEW "COH_DEV_L"."CONDITION_Q_UNQ_ASSET_DU_9_10" ("ORGANIZATION", "ASSET_TYPE", "SRC", "EAM_CLASS_ID", "EAM_CLASS_DESCRIPTION", "RAW_CLASS_ID", "RAW_CLASS_DESCRIPTION", "ASSET_COUNT", "CONDITION_Q1", "CONDITION_Q2", "CONDITION_Q3", "CONDITION_Q4", "CONDITION_Q5", "CONDITION_Q6", "CONDITION_Q7", "CONDITION_Q8", "CONDITION_Q9", "CONDITION_Q10") AS Select "ORGANIZATION","ASSET_TYPE","SRC","EAM_CLASS_ID","EAM_CLASS_DESCRIPTION","RAW_CLASS_ID","RAW_CLASS_DESCRIPTION","ASSET_COUNT","CONDITION_Q1","CONDITION_Q2","CONDITION_Q3","CONDITION_Q4","CONDITION_Q5","CONDITION_Q6","CONDITION_Q7","CONDITION_Q8","CONDITION_Q9","CONDITION_Q10" from DWO_WWO_UNQ_ASSET_CONDITION_Q_COMPARISION where eam_class_id in 
(Select class_id from ACTIVE_CLASS_CONDITION_Q where active_flag = 'Y') order by EAM_CLASS_DESCRIPTION
;
