--------------------------------------------------------
--  DDL for Table SNP_EXTRACT_COST_OVERRIDE_DU_9_10
--------------------------------------------------------

  CREATE TABLE "COH_DEV_L"."SNP_EXTRACT_COST_OVERRIDE_DU_9_10" ("CLASS_ID" VARCHAR2(10), "CLASS_DESCRIPTION" VARCHAR2(100), "CATEGORY_ID" VARCHAR2(10), "CATEGORY_DESCRIPTION" VARCHAR2(100), "REHAB_REPLACEMENT" VARCHAR2(20), "LABOR" VARCHAR2(11), "EQUIPMENT_COST" VARCHAR2(11), "GENERAL_CONDITION_5_PERCENT" VARCHAR2(11), "CONTRACT_OH_N_PROFIT_15_PERCENT" VARCHAR2(11), "ENG_CM_ADMIN_LEGAL_20_PERCENT" VARCHAR2(11), "SUB_TOTAL" VARCHAR2(11), "CONTIGENCY_25_PERCENT" VARCHAR2(11), "TOTAL_COST" VARCHAR2(11)) ;
