--------------------------------------------------------
--  DDL for Table SNP_EXTRACT_ASSET_TYPES_VALUES_DU_9_10
--------------------------------------------------------

  CREATE TABLE "COH_DEV_L"."SNP_EXTRACT_ASSET_TYPES_VALUES_DU_9_10" ("CLASS_ID" VARCHAR2(10), "CLASS_DESCRIPTION" VARCHAR2(100), "CATEGORY_ID" VARCHAR2(10), "CATEGORY_DESCRIPTION" VARCHAR2(100), "ESTIMATED_USEFUL_LIFE" NUMBER, "INITIAL_REINVESTMENT_ACTION" VARCHAR2(20), "MAX_NO_OF_REHABS" NUMBER, "REHAB_REVITALIZATION" NUMBER, "REHAB_EUL" NUMBER, "MAX_POTENTIAL_LIFE" NUMBER) ;
