--------------------------------------------------------
--  DDL for Table SNP_EXTRACT_COST_OVERRIDE_VALUES_DU_9_10
--------------------------------------------------------

  CREATE TABLE "COH_DEV_L"."SNP_EXTRACT_COST_OVERRIDE_VALUES_DU_9_10" ("CLASS_ID" VARCHAR2(10), "CLASS_DESCRIPTION" VARCHAR2(100), "CATEGORY_ID" VARCHAR2(10), "CATEGORY_DESCRIPTION" VARCHAR2(100), "REHAB_REPLACEMENT" VARCHAR2(20), "LABOR" NUMBER, "EQUIPMENT_COST" NUMBER, "GENERAL_CONDITION_5_PERCENT" NUMBER, "CONTRACT_OH_N_PROFIT_15_PERCENT" NUMBER, "ENG_CM_ADMIN_LEGAL_20_PERCENT" NUMBER, "SUB_TOTAL" NUMBER, "CONTIGENCY_25_PERCENT" NUMBER, "TOTAL_COST" NUMBER) ;
