--------------------------------------------------------
--  Constraints for Table VALIDATE_UNQ_ASSET_CONDITION_Q
--------------------------------------------------------

  ALTER TABLE "COH_DEV_T"."VALIDATE_UNQ_ASSET_CONDITION_Q" MODIFY ("EAM_CLASS_ID" NOT NULL ENABLE);
  ALTER TABLE "COH_DEV_T"."VALIDATE_UNQ_ASSET_CONDITION_Q" MODIFY ("CONDITION_Q" NOT NULL ENABLE);
  ALTER TABLE "COH_DEV_T"."VALIDATE_UNQ_ASSET_CONDITION_Q" MODIFY ("SRC_CONDITION_Q" NOT NULL ENABLE);
