--------------------------------------------------------
--  Constraints for Table WWO_COST_OVERRIDE_MASTER
--------------------------------------------------------

  ALTER TABLE "COH_DEV_T"."WWO_COST_OVERRIDE_MASTER" MODIFY ("CLASS_ID" NOT NULL ENABLE);
  ALTER TABLE "COH_DEV_T"."WWO_COST_OVERRIDE_MASTER" MODIFY ("CATEGORY_ID" NOT NULL ENABLE);
  ALTER TABLE "COH_DEV_T"."WWO_COST_OVERRIDE_MASTER" ADD CONSTRAINT "WWO_COST_OVERRIDE_MASTER_PK" PRIMARY KEY ("CLASS_ID", "CATEGORY_ID") USING INDEX  ENABLE;
