--------------------------------------------------------
--  Constraints for Table WWO_CONDITION_SET_Q_MASTER_KEY
--------------------------------------------------------

  ALTER TABLE "COH_DEV_T"."WWO_CONDITION_SET_Q_MASTER_KEY" MODIFY ("REF_CONDITION_Q_ID" NOT NULL ENABLE);
  ALTER TABLE "COH_DEV_T"."WWO_CONDITION_SET_Q_MASTER_KEY" MODIFY ("CLASS_ID" NOT NULL ENABLE);
  ALTER TABLE "COH_DEV_T"."WWO_CONDITION_SET_Q_MASTER_KEY" MODIFY ("CLASS_DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "COH_DEV_T"."WWO_CONDITION_SET_Q_MASTER_KEY" MODIFY ("REF_CONDITION_Q_NO" NOT NULL ENABLE);
  ALTER TABLE "COH_DEV_T"."WWO_CONDITION_SET_Q_MASTER_KEY" ADD CONSTRAINT "WWO_CONDITION_SET_Q_MASTER_KEY_PK" PRIMARY KEY ("CLASS_ID", "CLASS_DESCRIPTION", "REF_CONDITION_Q_NO") USING INDEX  ENABLE;
